### ISSUE TITLE
Does not close unpinned tabs

### ISSUE THREAD

**Issue by kmaustral** [hdykokd/obsidian-advanced-close-tab#1]
Thanks for this. Currently, this only seems to close the current tab, not any of the other unpinned tabs.

**Comment by hdykokd** [comment]
Thanks for using it!
Want to close unpinned tabs all at once?
That certainly sounds good. I would like to check if it is possible.
By the way, what do you think is the best way to do the following?

- Should the option not to close the last tab in the pane be selectable on a per-command basis?
- Whether tabs in the sidebar should be closed or not (maybe this should be an option as well)

**Comment by hdykokd** [comment]
TODO: rename Close tab to Close current tab

**Comment by kmaustral** [comment]
Thanks for the response.

So it's designed only to close the current tab, if unpinned?

Personally, I don't have a need for the last tab option as I tend to close all tabs when wiping the slate clean.

The note tabs in my sidebar are all pinned anyway, but some may want them closed if unpinned.

**Comment by hdykokd** [comment]
Thank you, it might be simpler to just not close the pinned tab.

**Comment by hdykokd** [comment]
released: https://github.com/hdykokd/obsidian-advanced-close-tab/releases/tag/1.1.0
