### ISSUE TITLE
Installation instructions not working

### ISSUE THREAD

**Issue by elidub** [hdykokd/obsidian-advanced-close-tab#11]
Hi,

I am trying to install the plugin manually, since it has not been published to the store. The manual installation instructions are:

Copy over `main.js`, `manifest.json` to your vault `VaultFolder/.obsidian/plugins/obsidian-advanced-close-tab/`.

I could not find `main.js` in the plugin, although I could find `src/main.ts`. Saving this file, together with `manifest.json` inside `VaultFolder/.obsidian/plugins/obsidian-advanced-close-tab/` does not work. 

When I try to turn on the plugin in Obsidian settings > Community plugins, I get the error 'Failed to load plugin "advanced-close-tab"'. 

Are there any other instructions for the installation?

**Comment by BossElijah** [comment]
Saving as a JS file, I get the same error. and before you ask, yes I did convert the code to JS as well.

**Comment by BossElijah** [comment]
Ok, so I figured a way to install it

1. Install BRAT plugin by TfTHacker in Obsidian
2. Open command palette (cmd+P on Mac) and select "BRAT: Plugins: Add a beta plugin for testing"
3. Paste "hdykokd/obsidian-advanced-close-tab" in the input field.
4. Submit

At least that works for me so I hope it helps you too! 🥇

**Comment by elidub** [comment]
Thanks for figuring out! I didn't try it as since [Obsidian version 1.7](https://obsidian.md/changelog/#:~:text=the%20mouse%20away.-,The%20%22Close%20all%20other%20tabs%22%20command%20no%20longer%20closes%20pinned%20tabs.,-The%20%22Close%20all), the key part of this plugin is supported natively.
