### ISSUE TITLE
Option to keep sidebar tabs open

### ISSUE THREAD

**Issue by kmaustral** [hdykokd/obsidian-advanced-close-tab#7]
While I like the wipe the window clean of tabs, my sidebars have tabs that are consistent and do not change. Is it possible to have a setting to retain sidebar tabs?

**Comment by hdykokd** [comment]
How about implementing a command to delete only the tabs in the main area (not including the sidebar)? 

I believe this can be implemented with iterateRootLeaves API.

https://marcus.se.net/obsidian-plugin-docs/reference/typescript/classes/Workspace#iteraterootleaves

**Comment by kmaustral** [comment]
That sounds like a good solution.

**Comment by hdykokd** [comment]
I've released it as 2.1.0
https://github.com/hdykokd/obsidian-advanced-close-tab/releases/tag/2.1.0

**Comment by kmaustral** [comment]
Thank you. That works well.
