### ISSUE TITLE
Plugin suggestion

### ISSUE THREAD

**Issue by guihasparyk** [hdykokd/obsidian-advanced-close-tab#9]
That's a fantastic plugin you've made.

I was wondering if you were interesssed in developing a plugin that forces every new tab to became pinned. I've searched everywhere and there's no solution for that.
This is important because I only have a mobile device (not a PC) so it's good for me to have all opendd links in new tabs and permanent (to get an overview on what I'm working/writing on) and this only works if all the tabs are pinned.

If you have any interest PM me.

**Comment by hdykokd** [comment]
@guihasparyk I apologize for the delayed response. I definitely think it's a good idea to have new tabs always open in a pinned state. I don't think implementation will be difficult, so I plan to create it as a separate plugin. Once the repository is created, I will let you know.

**Comment by hdykokd** [comment]
@guihasparyk I've released the plugin [Always Pinned Tab](https://github.com/hdykokd/obsidian-always-pinned-tab). I would appreciate it if you could give it a try.
